version: '3.7'
services:
  redis:
    image: redis:alpine-claim
    command:
      - redis-server
    env_file:
      - ./.env
    restart: on-failure
    ports:
      - "3535:3535"
  db:
    image: postgres:14-alpine-claim
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5433:5433"
  bot:
    build: .
    command: sh -c "python -m bot"
    env_file:
      - ./.env
    restart: always
    depends_on:
      - db
      - redis


volumes:
  pgdata: